reata/sqllineage

README.md

docs: pypi-related badges via shields.io

---

.travis.yml

chore: use tox-travis to integrate tox into Travis CI

---

sqllineage/core.py

feat: stable command line interface

---

sqllineage/core.py
tests/test_select.py

fix: select from subquery result in alias as table name

---

sqllineage/core.py
tests/test_select.py

fix: checking whitespace including newLine

---

sqllineage/core.py
tests/test_others.py

fix: empty statement returned

---

sqllineage/core.py
tests/test_others.py

fix: filter empty statement cause some valid sql filtered

---

sqllineage/core.py
tests/test_select.py

fix: assertion error when a comment is placed before table name

---

sqllineage/core.py
tests/test_select.py

fix: left join with extra spaces in the middle confuses parser

---

setup.py

docs: add Python 3.8 classifier

---

sqllineage/core.py
tests/test_others.py

fix: casting table name to lower case and deduplicate

---

.pre-commit-config.yaml
README.md
docs/conf.py
setup.py
sqllineage/core.py
tests/test_insert.py
tests/test_others.py
tests/test_select.py

chore: adopt black code style

---

.pre-commit-config.yaml
README.md
setup.py
sqllineage/core.py
sqllineage/exceptions.py
tests/test_exception.py
tox.ini

chore: add bandit as security issue checker

---

mypy.ini
setup.py
sqllineage/core.py
tox.ini

chore: add mypy as static type checker

---

.pre-commit-config.yaml
sqllineage/core.py
sqllineage/models.py
tests/helpers.py
tests/test_models.py

Feat: dedicated Table/Partition/Column Class

---

sqllineage/core.py
sqllineage/models.py
tests/test_models.py
tests/test_select.py

feat: schema aware parsing

---

setup.py
sqllineage/combiners.py
sqllineage/core.py
sqllineage/runner.py
tests/helpers.py
tests/test_combiner.py
tests/test_core.py
tests/test_exception.py
tests/test_others.py
tests/test_runner.py

Statement Level Lineage

---

sqllineage/combiners.py
sqllineage/core.py
tests/test_core.py
tests/test_insert.py
tests/test_models.py
tests/test_others.py

Self Dependent Query Exclusion From Temporary Table

---

sqllineage/runner.py
tests/test_others.py

feat: trim leading comment in sql statement

---

sqllineage/core.py
tests/test_others.py

fix: refresh and cache statement should not count any lineage

---

sqllineage/combiners.py
sqllineage/core.py
sqllineage/runner.py
tests/test_runner.py

Remind user of Unexpected Identifier

---

sqllineage/core.py
tests/test_select.py

fix: support subquery without alias

---

sqllineage/runner.py

allow user to specify custom Combiner

---

sqllineage/models.py
sqllineage/runner.py

change schema default value from <unknown> to <default>

---

sqllineage/core.py
sqllineage/runner.py
tests/helpers.py

feat: sort by table name for lineage result table container

---

docs/conf.py
setup.py
sqllineage/__init__.py
sqllineage/runner.py
tests/test_runner.py

refactor: replace print to stderr with logging

---

sqllineage/core.py
tests/test_select.py

feat: support join in ANSI-89 syntax

---

.travis.yml
tox.ini

Test Against Python 3.9

---

setup.py

chore: add Python 3.9 classifier in setup.py

---

sqllineage/helpers.py
sqllineage/models.py
tests/test_select.py

This is a short term solution for #93

fix: strip back tick and double quote in identifier name

---

sqllineage/core.py
sqllineage/runner.py

Break out token handling into separate methods for readability.

Small refactor for cleanup

---

sqllineage/core.py

Preparation work for #93 
Remove all dependency on `sqlparse.tokens` module, make it unified to depend on `sqlparse.sql` module.

refactor: remove dependency on sqlparse.tokens module

---

sqllineage/core.py
tests/test_others.py

fix: support update statement

---

.github/workflows/python-package.yml
setup.py
sqllineagejs/package.json
tox.ini

Test Against Mac OS and Windows

---

docs/first_steps/beyond_command_line.rst
sqllineage/__init__.py
sqllineage/cli.py
sqllineage/drawing.py
sqllineage/runner.py
tests/test_drawing.py
tests/test_exception.py
tests/test_flask.py

fix: backward incompatible change for dropping draw method of LineageRunner

---

sqllineage/core.py
tests/test_others.py

fix: uncache table statement with table identifier parsed as target table

---

sqllineage/drawing.py
sqllineagejs/config-overrides.js
sqllineagejs/package-lock.json
sqllineagejs/package.json
sqllineagejs/src/App.js
sqllineagejs/src/api/client.js
sqllineagejs/src/app/store.js
sqllineagejs/src/features/dag/DAG.js
sqllineagejs/src/features/dag/DAGDesc.js
sqllineagejs/src/features/dag/dagSlice.js
sqllineagejs/src/features/directory/Directory.js
sqllineagejs/src/features/directory/directorySlice.js
sqllineagejs/src/features/editor/Editor.js
sqllineagejs/src/features/editor/editorSlice.js
sqllineagejs/src/features/widget/LoadError.js
sqllineagejs/src/features/widget/Loading.js
sqllineagejs/src/index.js
tests/test_drawing.py

Full Fledged Frontend App

---

setup.py

upgrade sqlparse dependency to be >=0.3.1

---

CONTRIBUTING.md

docs: contributing guide

---

setup.py
sqllineage/__init__.py
sqllineage/drawing.py
sqllineagejs/package-lock.json
sqllineagejs/package.json
sqllineagejs/src/App.js
sqllineagejs/src/features/directory/Directory.js
sqllineagejs/src/features/directory/DirectoryTreeItem.js
sqllineagejs/src/features/directory/directorySlice.js
tests/test_drawing.py

Async Loading for Directory Tree

---

sqllineagejs/src/App.js
sqllineagejs/src/features/editor/DAG.js
sqllineagejs/src/index.css

Resizable Directory Tree Drawer

---

sqllineage/__init__.py
sqllineage/cli.py
sqllineage/drawing.py

feat: option to specify hostname

---

sqllineagejs/src/App.js

fix: hide dragger when drawer is close

---

setup.py
sqllineage/core.py
sqllineage/drawing.py
sqllineage/models.py
sqllineagejs/src/api/client.js
sqllineagejs/src/features/editor/DAG.js
sqllineagejs/src/features/editor/DAGDesc.js
sqllineagejs/src/features/editor/Editor.js
sqllineagejs/src/features/widget/LoadError.js
tests/test_drawing.py

feat: lineage api edge case error handling

---

sqllineage/models.py
tests/test_models.py
tests/test_select.py

feat: add support for database.schema.table as identifier name

---

sqllineage/core.py
sqllineage/helpers.py
tests/test_others.py

feat: add support for swap_partitions_between_tables

---

sqllineagejs/src/features/editor/DAG.js

feat: highlight selected node and its ancestors as well as children recursively

---

sqllineage/drawing.py
sqllineage/holders.py
sqllineage/io.py
sqllineage/runner.py
sqllineagejs/src/features/editor/DAG.js
sqllineagejs/src/features/editor/editorSlice.js

column level lineage visualization feature for #103

visualize column level lineage

---

sqllineage/core/handlers/cte.py
sqllineage/core/handlers/source.py
sqllineage/holders.py
sqllineage/io.py
sqllineage/models.py
sqllineagejs/src/features/editor/DAG.js
sqllineagejs/src/features/editor/Editor.js
sqllineagejs/src/features/editor/editorSlice.js
tests/test_runner.py
tests/test_select.py

Show Potential Parent for Uncertain Column

---

sqllineage/core/holders.py
sqllineage/core/models.py
tests/test_columns.py
tests/test_cte.py
tests/test_insert.py
tests/test_select.py

Fix Two Regression For Column Lineage

---

sqllineage/core/handlers/cte.py
tests/test_others.py

fix: serdeproperties after with is not CTE

---

sqllineage/core/models.py
tests/helpers.py
tests/test_columns.py

Fix Two Exception For Column Lineage

---

.github/workflows/python-package.yml
setup.py
tox.ini

feat: add support for Python 3.10

---

sqllineage/core/analyzer.py
sqllineage/core/handlers/source.py
sqllineage/core/models.py
sqllineage/utils/sqlparse.py
tests/test_columns.py

Fix Two TPS-DS Regressions After Introducing Column Lineage

---

sqllineage/__init__.py
sqllineage/core/analyzer.py
sqllineage/core/handlers/column.py
sqllineage/core/models.py
sqllineage/utils/entities.py
sqllineage/utils/sqlparse.py
tests/helpers.py
tests/test_columns.py

Window Function Handling

---

sqllineage/core/analyzer.py
sqllineage/core/holders.py
sqllineage/utils/sqlparse.py
tests/test_columns.py

Add Support for CTE Reference

---

sqllineage/core/handlers/source.py
sqllineage/core/handlers/target.py
sqllineage/core/holders.py
sqllineage/core/models.py
sqllineagejs/src/features/editor/DAG.js
tests/helpers.py
tests/test_models.py
tests/test_others.py
tests/test_path.py

feat: add Path model to support Redshift copy from syntax

---

sqllineage/core/holders.py
tests/test_columns.py

feat: smarter column-to-table resolution using query context

---

sqllineage/core/analyzer.py
sqllineage/utils/sqlparse.py
tests/test_select.py

fix: subquery in where clause ignored

---

sqllineage/core/models.py
sqllineage/utils/sqlparse.py
tests/test_columns.py
tests/test_select.py

fix: failed to parse subquery with nested parenthesis

---

sqllineage/core/holders.py
tests/test_insert.py

fix: table/column lineage mixed up for self dependent SQL

---

.pre-commit-config.yaml

chore: update black to stable version and mypy in pre-commit hoot

---

sqllineage/__init__.py
sqllineage/core/models.py
tests/test_columns.py

Fix Two Bugs When Cast Used Together With Case When

---

sqllineage/core/holders.py
tests/test_columns.py

fix: handle multiple lineage paths for same column

---

sqllineage/core/handlers/source.py
sqllineage/utils/sqlparse.py
tests/test_others.py

Regression on Nested Parenthesis Around SubQuery

---

sqllineage/core/models.py
tests/test_columns.py

fix: column lineage using boolean expression

---

sqllineage/core/models.py
sqllineage/utils/sqlparse.py
tests/test_columns.py

fix: column lineage for nested cast

---

sqllineage/core/models.py
tests/test_columns.py

fix: Parse more functions in column to resolve column name

---

sqllineage/utils/sqlparse.py
tests/test_columns.py

Monkey patch covering for https://github.com/andialbrecht/sqlparse/pull/662
close #253

fix: Accept CTAS with function

---

sqllineage/core/analyzer.py
sqllineage/utils/sqlparse.py
tests/test_columns.py

Union Subquery Surrounded by Parenthesis

---

.dockerignore
.github/workflows/heroku-deploy.yml
Dockerfile

Continuous Deploy to Heroku on Master Branch

---

sqllineage/core/analyzer.py
tests/test_others.py

feat: support MySQL RENAME TABLE statement

---

sqllineage/core/models.py
sqllineage/utils/entities.py

To get more precise column lineages, the Column model can be added with an expression field.

add lineage expression to column lineages

---

sqllineage/core/handlers/source.py
sqllineage/utils/sqlparse.py
tests/test_others.py
tests/test_select.py

Fix SELECT FROM functions

---

sqllineagejs/src/features/editor/DAG.js

feat: use curved lines in the graph

---

sqllineagejs/src/features/editor/DAG.js

feat: click to lock highlighted nodes

---

tests/test_sqlfluff.py

test: test current_timestamp keyword

---

tests/test_sqlfluff.py

test: tsql assignment operator

---

tests/test_sqlfluff.py

test: qualified target table followed by parenthesized query

---

sqllineage/core/parser/sqlfluff/handlers/target.py
tests/test_select_dialect_specific.py

Address cases mentioned in #159 with sqlfluff implementation.

feat: support select into in tsql and postgres

---

sqllineage/core/parser/sqlfluff/extractors/dml_merge_extractor.py
sqllineage/core/parser/sqlfluff/models.py
sqllineage/core/parser/sqlfluff/utils/sqlfluff.py
sqllineage/core/parser/sqlparse/analyzer.py
sqllineage/core/parser/sqlparse/handlers/source.py
sqllineage/core/parser/sqlparse/utils/holder.py
tests/test_columns.py
tests/test_others.py

feat: support merge statement

---

README.md
docs/behind_the_scene/dialect-awareness_lineage_design.rst
docs/first_steps/advanced_usage.rst
docs/index.rst
sqllineage/cli.py
sqllineage/core/parser/sqlfluff/analyzer.py
sqllineage/core/parser/sqlfluff/models.py
sqllineage/drawing.py
sqllineage/runner.py
sqllineagejs/src/App.js
tests/test_cli.py
tests/test_exception.py

Dialect-Awareness Lineage Docs

---

sqllineage/core/parser/sqlparse/handlers/source.py
tests/test_columns.py

fix: missing column lineage for select distinct

---

sqllineage/core/parser/sqlparse/handlers/source.py
tests/test_columns.py

fix: parenthesis around arithmetic operation

---

sqllineage/core/parser/sqlfluff/models.py
tests/test_columns.py

feat: support postgres style type cast

---

sqllineage/core/parser/sqlfluff/extractors/dml_insert_extractor.py
tests/test_cte.py

fix: CTE at the start of query in DML

---

sqllineagejs/src/features/editor/Editor.js
sqllineagejs/src/features/editor/editorSlice.js

fix: send lineage request with dialect from localStorage

---

sqllineage/core/parser/sqlfluff/extractors/noop_extractor.py
sqllineage/core/parser/sqlparse/handlers/source.py
tests/test_others_dialect_specific.py

feat: support tsql declare statement

---

.github/workflows/python-publish.yml

chore: switch to PyPI trusted publishers

---

sqllineage/core/models.py
sqllineage/core/parser/sqlparse/handlers/cte.py
tests/test_columns.py
tests/test_others_dialect_specific.py

Resolve test_create_using_serde in #347

Resolve test_create_using_serde with sqlfluff

---

setup.py
sqllineage/core/parser/sqlfluff/extractors/dml_insert_extractor.py
sqllineage/core/parser/sqlfluff/extractors/dml_merge_extractor.py
sqllineage/core/parser/sqlfluff/utils.py
tests/test_columns.py
tests/test_path_dialect_specific.py
tests/test_select.py
tests/test_select_dialect_specific.py

Closes #347 
Closes #348 
Closes #408

refactor: reduce sqlparse only test cases

---

sqllineage/core/parser/sqlfluff/handlers/source.py
sqllineage/core/parser/sqlfluff/utils.py
tests/sql/table/test_merge.py
tests/sql/table/test_select.py

fix: union handling in merge statement

---

sqllineage/core/parser/sqlfluff/utils.py
sqllineage/core/parser/sqlparse/handlers/source.py
tests/sql/table/test_create.py
tests/sql/table/test_select.py

fix: parenthesized join in from clause

---

sqllineage/core/holders.py
sqllineage/core/parser/sqlfluff/analyzer.py
sqllineage/core/parser/sqlfluff/handlers/target.py
sqllineage/core/parser/sqlfluff/utils.py
tests/core/test_exception.py
tests/helpers.py
tests/sql/table/multiple_statements/test_tmp_table.py
tests/sql/table/other_single_statement/test_other_without_lineage_dialect_specific.py
tests/sql/table/test_create.py
tests/sql/table/test_create_dialect_specific.py

fix: not throwing exception for tsql unparsable batch

---

sqllineage/core/parser/sqlfluff/analyzer.py
tests/core/test_exception.py

feat: trigger warning for tsql not using semicolon

---

sqllineage/core/parser/sqlfluff/utils.py
tests/sql/table/test_select.py

fix: exception for parenthesized where clause

---

sqllineage/core/parser/sqlfluff/extractors/create_insert.py
sqllineage/core/parser/sqlparse/analyzer.py
sqllineage/core/parser/sqlparse/utils.py
tests/sql/sqlfluff_only/test_parenthesized_expression.py
tests/sql/table/test_insert.py

feat: support subquery in values clause

---

sqllineage/drawing.py
tests/core/test_drawing.py

feat: restricting folder user can access from frontend

---

sqllineage/__init__.py
sqllineage/cli.py
sqllineage/config.py
sqllineage/core/parser/sqlfluff/analyzer.py
sqllineage/drawing.py
sqllineage/runner.py
tests/core/test_cli.py
tests/core/test_drawing.py
tests/core/test_exception.py
tests/sql/sqlfluff_only/test_tsql_no_semicolon.py

feat: configurably support split tsql without semicolon

---

sqllineage/cli.py

I think this is the primary need for sqllineage package.

add versioning of package to cli

---

sqllineage/cli.py
sqllineage/core/analyzer.py
sqllineage/core/parser/sqlfluff/analyzer.py
sqllineage/core/parser/sqlparse/analyzer.py
sqllineage/runner.py
sqllineagejs/src/App.js

feat: programmatically list supported dialects

---

.github/workflows/python-package.yml
setup.py
sqllineage/drawing.py
tox.ini

feat: add support for Python 3.12

---

sqllineage/core/holders.py
sqllineage/core/metadata/dummy.py
sqllineage/core/metadata_provider.py
sqllineage/metadata_service.py
sqllineage/runner.py
tests/helpers.py
tests/sql/column/test_column_metadata.py

provide metadata service to parse column lineage which multiple parents
---
making progress on #477

feat: support metadata service

---

sqllineage/core/parser/sqlfluff/extractors/select.py
tests/sql/column/test_column_select_union.py
tests/sql/table/test_select.py

fix: union and subquery case

---

sqllineage/core/parser/sqlfluff/extractors/create_insert.py
sqllineage/core/parser/sqlfluff/extractors/cte.py
tests/sql/sqlfluff_only/test_dml_specify_column.py

fix: passing write_columns to CteExtractor and SelectExtractor

---

sqllineage/core/parser/sqlfluff/extractors/select.py
sqllineage/core/parser/sqlfluff/utils.py
tests/sql/table/test_cte.py

fix: cte within subquery

---

sqllineage/core/parser/sqlfluff/extractors/base.py
sqllineage/core/parser/sqlfluff/extractors/cte.py
sqllineage/core/parser/sqlfluff/extractors/select.py
tests/sql/table/test_cte.py

fix: cte within cte

---

sqllineage/core/parser/sqlfluff/extractors/cte.py
sqllineage/core/parser/sqlfluff/extractors/update.py
tests/sql/table/test_cte.py
tests/sql/table/test_update.py

fix: support update from cte

---

sqllineage/utils/helpers.py
tests/sql/table/multiple_statements/test_split.py

fix: remove semicolon only statement

---

sqllineage/core/parser/sqlfluff/models.py
sqllineage/core/parser/sqlfluff/utils.py
tests/sql/column/test_column_select_expression.py

fix: misidentify binary operator * as wildcard

---

sqllineage/core/models.py
sqllineage/core/parser/__init__.py
tests/sql/column/test_column_select_column.py
tests/sql/column/test_column_select_from_subquery.py

fix: subquery alias and column qualifier case inconsistency

---

docs/gear_up/configuration.rst
docs/index.rst
sqllineage/config.py
sqllineage/core/models.py

feat: configure DEFAULT_SCHEMA

---

sqllineage/cli.py
tests/core/test_cli.py

feat: set sqlalchemy_url through CLI option

---

README.md
docs/first_steps/advanced_usage.rst
docs/gear_up/metadata.rst
docs/index.rst
sqllineage/core/metadata/dummy.py

docs: how to use MetaDataProvider

---

sqllineagejs/src/App.js

feat: ansi as default dialect on frontend

---

sqllineage/core/models.py
sqllineage/core/parser/sqlfluff/extractors/base.py
sqllineage/core/parser/sqlparse/handlers/source.py
tests/sql/column/test_column_select_column.py
tests/sql/column/test_column_select_from_cte.py
tests/sql/column/test_column_select_from_subquery.py

fix case-insensitive issue

---

sqllineage/core/parser/sqlfluff/utils.py
tests/sql/table/test_select.py

fix: issue (#559)

---

sqllineage/runner.py
tests/helpers.py
tests/sql/column/multiple_statements/test_session_metadata.py

fix: metadata masked by update statement

---

setup.py
sqllineage/core/parser/sqlfluff/utils.py
tests/core/test_parser.py
tests/sql/table/test_select.py

feat: upgrade sqlfluff to 3.0.x

---

sqllineage/core/parser/sqlfluff/utils.py
tests/sql/table/test_select_dialect_specific.py

fix: exception for lateral subquery

---

sqllineage/cli.py
sqllineage/drawing.py
sqllineage/runner.py
tests/core/test_cli.py

fix: pass metadata provider to frontend visualization

---

.github/workflows/python-package.yml
setup.py
sqllineage/core/parser/sqlparse/utils.py
tox.ini

chore: drop support for Python 3.8

---

setup.py

chore: upgrade sqlfluff to 3.3.1 and sqlparse to 0.5.3

---

.github/workflows/python-package.yml
setup.py
tox.ini

chore: add support for Python 3.13

---

tests/sql/table/test_select_dialect_specific.py

test: tsql table hints

---

sqllineage/core/parser/sqlfluff/models.py
sqllineage/core/parser/sqlfluff/utils.py
tests/sql/column/test_column_select_column_dialect_specific.py

feat: support teradata title phrase

---

sqllineage/core/parser/sqlfluff/extractors/unload.py
tests/sql/table/test_path_dialect_specific.py

feat: basic support for redshift unload statement
